### ISSUE TITLE
Potentially non-functional in Atom v1.7.3

### ISSUE THREAD

**Issue by pushasha** [stan3/gherkin-table-formatter#2]
Not sure if I'm doing something wrong, but I can't seem to get any tables to format in Atom v1.7.3. For instance, I have the following table in an `Examples` section of my feature file:

``` gherkin
Examples:
    | before | after |
    | on | off |
    | incomplete | complete |
```

If I use my cursor to highlight everything below the `Examples:` line, go to `Packages` in the Atom menu bar, go to `Gherkin Table Formatter`, then select `Format`, nothing happens. I have also tried using the keyboard shortcut, but to no avail.

The only packages I have installed are the ones that come with Atom by default, the [language-gherkin](https://atom.io/packages/language-gherkin) package, and this one. I also made sure to specify the applicable file grammars in the `Gherkin Grammar Scopes` section of the package settings.

**Comment by perpetuumstef** [comment]
I'm having this issue as well on Atom v1.13.0, running on Mac. A colleague using the same package in windows is not experiencing this issue (I'm not suggesting that it stems from the OS it's installed on).

UPDATE: solved the issue by updating the package settings grammar scope (see screenshot below). To find the current "Scopes at Cursor", run 'Editor: Log Cursor Scope' and use the scopes in the package settings (comma separated).

![image](https://cloud.githubusercontent.com/assets/5889140/22028085/ff350602-dca3-11e6-9023-36212a2d3787.png)
